const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.resolve(__dirname, "../ui/index.html"), "utf8");
const css = fs.readFileSync(path.resolve(__dirname, "../ui/styles.css"), "utf8");
const app = fs.readFileSync(path.resolve(__dirname, "../ui/app.js"), "utf8");
const craftService = fs.readFileSync(path.resolve(__dirname, "../src/services/craftService.js"), "utf8");
const componentService = fs.readFileSync(path.resolve(__dirname, "../src/services/craftTradeupWithComponentsService.js"), "utf8");
const uiServer = fs.readFileSync(path.resolve(__dirname, "../src/uiServer.js"), "utf8");

function main() {
  assert.match(html, /id="craftAddPresetBtn"[^>]*title="添加配方"[^>]*aria-label="添加配方"/);
  assert.doesNotMatch(html, /id="craftAssistApplyBtn"/);
  assert.match(html, /id="craftAssistEditorModal"/);
  assert.match(html, /id="craftAssistEditorLeft"/);
  assert.match(html, /id="craftAssistEditorSearch"/);
  assert.match(html, /id="craftAssistEditorPrediction"/);
  assert.match(html, /id="craftAssistMainRoleGroup"[^>]*data-role="main"/);
  assert.match(html, /id="craftAssistAuxRoleGroup"[^>]*data-role="aux"/);
  assert.doesNotMatch(html, /id="craftAssist(?:Main|Aux)RoleBtn"|craft-assist-editor-role-tabs/);
  assert.match(html, /data-rarity-tag="1"[^>]*>消费级</);
  assert.match(html, /data-rarity-tag="2"[^>]*>工业级</);
  assert.match(html, /data-rarity-tag="3"[^>]*>军规级</);
  assert.match(html, /id="craftAssistWarehouseSourceBtn"/);
  assert.match(html, /id="craftAssistOutcomeModal"[^>]*role="dialog"/);
  assert.match(html, /id="craftAssistOutcomeModalRarityBadge"/);
  assert.doesNotMatch(html, /craftAssistOutcomeModalStatusBadge|可精修/);
  assert.match(html, /id="craftAssistOutcomeModalWearLabel"/);
  assert.match(html, /id="craftAssistOutcomeModalAbsoluteValue"/);
  assert.match(html, /id="craftAssistOutcomeAbsoluteWear"/);
  assert.match(html, /id="craftAssistOutcomeRelativeWear"/);
  assert.doesNotMatch(html, /id="craftAssistOutcomeConverter"/);
  assert.match(css, /\.craft-assist-editor-card\s*\{[^}]*grid-template-rows:/s);
  assert.match(css, /\.craft-assist-editor-columns\s*\{[^}]*grid-template-columns:/s);
  assert.match(css, /\.craft-assist-editor-column\s*\{[^}]*overflow:\s*hidden/s);
  assert.match(css, /body\.theme-inkblue \.craft-assist-editor-modal \.craft-assist-item[\s\S]*background:\s*rgba\(12, 17, 25, 0\.9\)/s);
  assert.match(css, /\.craft-assist-preset-list\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fill,/s);
  assert.match(css, /\.craft-assist-editor-left\s+\.craft-assist-material-card-list\s*\{[^}]*grid-template-columns:\s*repeat\(4,/s);
  const editorWidth = css.match(/\.craft-assist-editor-card\s*\{[^}]*width:\s*min\((\d+)px,/s);
  assert.ok(editorWidth && Number(editorWidth[1]) > 1320, "craft assist editor should be wider than 1320px");
  assert.match(css, /\.craft-assist-outcome-modal-card\s*\{/);
  assert.match(css, /\.craft-assist-editor-role-btn\.active\s*\{[\s\S]*background:\s*transparent;/);
  assert.match(css, /\.craft-assist-editor-role-group\.active\s+\.craft-assist-role-tag\s*\{[\s\S]*border-color:/);
  assert.match(css, /body\.theme-inkblue \.craft-assist-editor-modal \.craft-assist-editor-role-group\.active\s*\{[\s\S]*border-color:/);
  assert.doesNotMatch(css, /\.craft-assist-editor-role-btn\.active\s*\{[^}]*background:\s*var\(--accent\)/);
  assert.doesNotMatch(app, /填写目标相对磨损后显示预测/);
  assert.doesNotMatch(app, /ui\.craftAssistEditorPrediction\.classList\.toggle\("hidden",\s*tagMode\)/);
  assert.match(app, /ui\.craftAssistEditorPrediction\.classList\.remove\("hidden"\)/);
  assert.match(app, /tagMode\s*\?\s*"当前配方已选所有（标签级）"/);
  assert.match(app, /tagMode[\s\S]*标签模式不进行产物预测/);
  assert.doesNotMatch(css, /\.craft-assist-editor-modal\.rarity-tag-mode \.craft-assist-editor-columns\s*\{/);
  assert.match(app, /ui\.craftAssistOutcomeModal\.classList\.remove\("hidden"\)/);
  assert.match(app, /ui\.craftAssistOutcomeModalWearLabel\.textContent\s*=/);
  assert.match(app, /ui\.craftAssistOutcomeModalAbsoluteValue\.textContent\s*=/);
  assert.match(app, /ui\.craftAssistOutcomeError\.classList\.add\("hidden"\)/);
  assert.match(app, /ui\.craftAssistOutcomeError\.classList\.remove\("hidden"\)/);
  assert.match(app, /ui\.craftAssistOutcomeAbsoluteWear\.oninput\s*=\s*\(\)\s*=>\s*\{[\s\S]*sanitizeCraftAssistOutcomeWearDigits[\s\S]*updateCraftAssistOutcomeConverter\(\)/);
  assert.match(app, /ui\.craftAssistTargetWear\.value\s*=\s*pair\s*\?\s*pair\.target_wear_raw\s*:\s*"";/);
  assert.match(app, /if\s*\(!open\)\s*\{[\s\S]*renderCraftAssistOutcomeModal\(\);[\s\S]*return;/);
  assert.match(app, /item\.onclick\s*=\s*\(evt\)\s*=>[\s\S]*activateRole\(\)/);
  assert.match(app, /item\.classList\.toggle\("active",[\s\S]*state\.craftAssistPickRole/);
  assert.match(app, /state\.craftAssistTargetWear\s*=\s*null;[\s\S]*invalidateCraftAssistEditorPrediction\(\{refresh:\s*false\}\)/);
  assert.match(app, /predictorDraft\.payload\.wear_approach_mode\s*=\s*"infinite"/);
  assert.match(app, /按相对磨损升序选取/);
  assert.match(app, /normalize_special_quality:\s*true/);
  assert.match(craftService, /normalizeSpecialQuality\s*=\s*false/);
  assert.match(componentService, /normalizeSpecialQuality/);
  assert.match(uiServer, /body\.normalize_special_quality/);
  console.log("craft-assist-three-column-contract tests passed");
}

main();
